# Input any string here. Supports colour codes.
ban-reason: "change me"
# Uses the Litebans format
ban-length: "18d"
# The delay before they are banned in seconds
ban-delay: 3
# This will turn off console messages
console-log: true